# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SigninDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SigninDialog(object):
    def setupUi(self, SigninDialog):
        SigninDialog.setObjectName("SigninDialog")
        SigninDialog.resize(513, 417)
        self.sign_in_label = QtWidgets.QLabel(SigninDialog)
        self.sign_in_label.setGeometry(QtCore.QRect(200, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.sign_in_label.setFont(font)
        self.sign_in_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sign_in_label.setObjectName("sign_in_label")
        self.username_label = QtWidgets.QLabel(SigninDialog)
        self.username_label.setGeometry(QtCore.QRect(70, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(SigninDialog)
        self.password_label.setGeometry(QtCore.QRect(70, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.forgot_pwd_button = QtWidgets.QPushButton(SigninDialog)
        self.forgot_pwd_button.setGeometry(QtCore.QRect(60, 240, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setUnderline(True)
        self.forgot_pwd_button.setFont(font)
        self.forgot_pwd_button.setStyleSheet("color : blue;")
        self.forgot_pwd_button.setFlat(True)
        self.forgot_pwd_button.setObjectName("forgot_pwd_button")
        self.confirm_button = QtWidgets.QPushButton(SigninDialog)
        self.confirm_button.setGeometry(QtCore.QRect(80, 300, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.confirm_button.setFont(font)
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(SigninDialog)
        self.cancel_button.setGeometry(QtCore.QRect(290, 300, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.username_input_field = QtWidgets.QLineEdit(SigninDialog)
        self.username_input_field.setGeometry(QtCore.QRect(60, 120, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(13)
        self.username_input_field.setFont(font)
        self.username_input_field.setObjectName("username_input_field")
        self.pwd_input_field = QtWidgets.QLineEdit(SigninDialog)
        self.pwd_input_field.setGeometry(QtCore.QRect(60, 190, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(13)
        self.pwd_input_field.setFont(font)
        self.pwd_input_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_input_field.setObjectName("pwd_input_field")
        self.username_error_label = QtWidgets.QLabel(SigninDialog)
        self.username_error_label.setGeometry(QtCore.QRect(180, 90, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.username_error_label.setFont(font)
        self.username_error_label.setStyleSheet("color: red;")
        self.username_error_label.setObjectName("username_error_label")

        self.username_error_label.hide() 

        self.password_error_label = QtWidgets.QLabel(SigninDialog)
        self.password_error_label.setGeometry(QtCore.QRect(180, 160, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.password_error_label.setFont(font)
        self.password_error_label.setStyleSheet("color: red;")
        self.password_error_label.setObjectName("password_error_label")
        self.password_error_label.hide()

        self.retranslateUi(SigninDialog)
        QtCore.QMetaObject.connectSlotsByName(SigninDialog)

    def retranslateUi(self, SigninDialog):
        _translate = QtCore.QCoreApplication.translate
        SigninDialog.setWindowTitle(_translate("SigninDialog", "SigninDialog"))
        self.sign_in_label.setText(_translate("SigninDialog", "Sign in"))
        self.username_label.setText(_translate("SigninDialog", "Username"))
        self.password_label.setText(_translate("SigninDialog", "Password"))
        self.forgot_pwd_button.setText(_translate("SigninDialog", "Forgot Password"))
        self.confirm_button.setText(_translate("SigninDialog", "Confirm"))
        self.cancel_button.setText(_translate("SigninDialog", "Cancel"))
        self.username_error_label.setText(_translate("SigninDialog", "*username_error_label"))
        self.password_error_label.setText(_translate("SigninDialog", "*password_error_label"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SigninDialog = QtWidgets.QDialog()
    ui = Ui_SigninDialog()
    ui.setupUi(SigninDialog)

    # Create an instance of your QDialog
    dialog = SigninDialog

    # Connect the exit_button click event to close the dialog
    ui.cancel_button.clicked.connect(dialog.close)

    SigninDialog.show()
    sys.exit(app.exec_())
